name: Periodic Style Checks

on:
  - push
  schedule:
    - cron: "0 1 * * 4" # Runs at 01:00 AM on every Wednesday

jobs:
  vale:
    name: Style checker
    runs-on: ubuntu-22.04
    defaults:
        run:
            shell: bash
            working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Run vale on RST and MD files        
        run: |
          make vale TARGET="*.rst *.md" 

